### ISSUE TITLE
PHP 5.3 support

### ISSUE THREAD

**Issue by djordje** [jails/li3_behaviors#2]
Is it necessary to drop PHP 5.3 support?

**Comment by jails** [comment]
Well, I hesitated a long time to move to `traits`. But it looks like it's the only "tool" which allow to put together a bunch of logic without having too many custom "base models".

According to http://php.net/releases/5_3_20.php, the 5.3 series seems to reach the end of it life in a couple of month so I decide to move on and starting using 5.4 seeing that the 5.5 is on the road.

**Comment by djordje** [comment]
Yes, traits are very useful, but I think it's to early for PHP 5.4 in production, because too many hosts still runs on PHP 5.3 :(

**Comment by jails** [comment]
To be honest, this code is not ready to be used in production too ;-)
There's not that much shared hosts which doesn't support PHP 5.4 currently. And for dedicated hosts, upgrading form 5.3 to 5.4 still a minor upgrade. Most PHP 5.3 code should work out of the box using PHP 5.4. There's no reason to not updrade imo.

**Comment by djordje** [comment]
I've created `php-5.3` branch of this lib and (li3_tree, li3_access) to support my `li3_usermanager` on php 5.3+.

I can continue to update them to follow changes on master.
I just thinking is it better to PR them to your repos (to separate branch) so we have everything in one place?

**Comment by jails** [comment]
Personnaly I would like to keep the master branch on PHP 5.4. but you should now have all access to continue to update the `php-5.3` branch if you are motivated. ;-)

**Comment by djordje** [comment]
Yes PHP 5.4 should be in `master` and PHP 5.3 should be optional.
